# server.py
from __future__ import annotations

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from lucy_kernel import LucyKernel

app = FastAPI(title="Lucy STUR Backend")

# global kernel instance
kernel = LucyKernel()

# allow your GitHub Pages front-end to talk to this backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # you can lock this down to your domain later
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class MessageIn(BaseModel):
    message: str


class CodeIn(BaseModel):
    description: str


@app.post("/message")
def message_endpoint(payload: MessageIn):
    """
    Main chat endpoint for Lucy.
    Your lucy.html calls this when a backend URL is set.
    """
    reply = kernel.step(payload.message)
    return {"reply": reply, "termination_token": "main"}


@app.post("/generate_code")
def generate_code_endpoint(payload: CodeIn):
    """
    Simple code generator stub.
    Your lucy.html already knows how to call /generate_code;
    this returns a structured filename + code string.
    """
    desc = payload.description.strip()
    lower = desc.lower()

    if "python" in lower:
        filename = "script.py"
    elif "html" in lower:
        filename = "page.html"
    elif "js" in lower or "javascript" in lower:
        filename = "script.js"
    else:
        filename = "lucy_script.py"

    code = f'''# Autogenerated by Lucy backend
# Description:
#   {desc}

def main():
    print("Lucy backend stub running for: {desc}")

if __name__ == "__main__":
    main()
'''

    return {"filename": filename, "code": code}
