#!/usr/bin/env python3
"""
μ_R Derivation for L_X Stabilization
======================================

Determines whether μ_R (the R-field mass parameter) can be computed
from first principles within STUR, fixing the L_X minimum.

Three approaches:
A. Coleman-Weinberg: μ_R from radiative symmetry breaking
B. Dimensional transmutation: μ_R from KK scale
C. Self-consistency: μ_R from v_R = 3/L_X constraint + EW scale
"""

import numpy as np

v_EW = 246.22
m_t = 172.57
m_H = 125.10
m_W = 80.379
m_Z = 91.188
g_2 = 0.652
g_Y = 0.357
alpha_s = 0.1179
M_Pl = 1.22e19
L_X = 3.0 / v_EW
M_KK = 2 * np.pi / L_X

def header(title):
    print(f"\n{'=' * 72}")
    print(f"  {title}")
    print(f"{'=' * 72}\n")

# =====================================================================
header("SECTION 1: Approach A — Coleman-Weinberg Mechanism")

print("  If μ_R² = 0 at tree level (classically conformal R-field),")
print("  radiative corrections generate an effective μ_R through")
print("  the Coleman-Weinberg mechanism.")
print()

# CW potential: V_eff = (B/4)φ⁴(ln(φ²/v²) - 1/2) + Bv⁴/4
# where B = (1/64π²v⁴)Σ(-1)^{2s}(2s+1)m_i⁴
# Minimum at φ = v with m_H² = 2Bv²

# For the R-field, the relevant loops are:
# - Gauge: W/Z couple to R through SU(2)×U(1)
# - Top quark: through Yukawa coupling to R
# - Self-coupling: R⁴ term

# The effective μ_R² from CW:
# μ_R² = -B_R × v_R² where B_R = (1/16π²) Σ n_i g_i⁴

# R-field gauge coupling: g_R ~ g_2 (from SU(2) sector)
# Using the SM Higgs analogy scaled to R-field:
B_gauge = (3 / (64 * np.pi**2)) * (2 * g_2**4 + (g_2**2 + g_Y**2)**2)
B_top = -(3 / (16 * np.pi**2)) * (m_t / v_EW)**4  # top Yukawa
B_total = B_gauge + B_top

mu_R_CW_sq = abs(B_total) * v_EW**2
mu_R_CW = np.sqrt(mu_R_CW_sq)

print(f"  B_gauge = {B_gauge:.6f}")
print(f"  B_top   = {B_top:.6f}")
print(f"  B_total = {B_total:.6f}")
print(f"  |μ_R²|  = |B| × v_EW² = {mu_R_CW_sq:.1f} GeV²")
print(f"  μ_R(CW) = {mu_R_CW:.2f} GeV")
print()

# Predicted L_X from this μ_R
# From lx_stabilization.py: L_* = sqrt(2A/(9μ_R²))
# where A ~ 100 (Casimir sum)
A_casimir = 100.8  # from lx_stabilization.py
L_star_CW = np.sqrt(2 * A_casimir / (9 * mu_R_CW**2))
M_KK_CW = 2 * np.pi / L_star_CW

print(f"  L_*(CW) = sqrt(2×{A_casimir:.0f}/(9×{mu_R_CW:.1f}²)) = {L_star_CW:.4f} GeV⁻¹")
print(f"  M_KK(CW) = {M_KK_CW:.1f} GeV")
print(f"  Target: L_X = {L_X:.4f} GeV⁻¹, M_KK = {M_KK:.1f} GeV")
print(f"  Ratio L_*/L_X = {L_star_CW/L_X:.2f}")

# =====================================================================
header("SECTION 2: Approach B — Dimensional Transmutation on S¹/Z₃")

print("  In 5D, the R-field has a bulk mass M₅. After KK reduction:")
print("    μ_R² = M₅² + corrections from KK modes")
print()
print("  If M₅ = 0 by a symmetry (e.g., shift symmetry broken by Z₃),")
print("  then μ_R is generated by the KK tower:")
print("    μ_R² ~ g²/(16π²) × (2π/L_X)² = g² M_KK²/(16π²)")

for name, g in [("g_2", g_2), ("g_Y", g_Y), ("g_s", np.sqrt(4*np.pi*alpha_s))]:
    mu_dim = g * M_KK / (4 * np.pi)
    L_star = np.sqrt(2 * A_casimir / (9 * mu_dim**2))
    print(f"  {name} = {g:.3f}: μ_R = g×M_KK/(4π) = {mu_dim:.1f} GeV → L_* = {L_star:.4f} GeV⁻¹ (ratio: {L_star/L_X:.2f})")

# =====================================================================
header("SECTION 3: Approach C — Self-Consistency with v_R = 3/L_X")

print("  The R-field potential V(R) = -μ_R²|R|² + λ_R|R|⁴")
print("  has minimum at v_R = μ_R/√(2λ_R)")
print()
print("  Combined with topological constraint v_R = 3/L_X:")
print("    μ_R/√(2λ_R) = 3/L_X")
print("    μ_R = 3√(2λ_R)/L_X")
print()
print("  If λ_R ~ λ_SM (Higgs quartic) ≈ 0.13:")

lambda_SM = m_H**2 / (2 * v_EW**2)
print(f"    λ_SM = m_H²/(2v²) = {lambda_SM:.4f}")

mu_R_self = 3 * np.sqrt(2 * lambda_SM) / L_X
L_star_self = np.sqrt(2 * A_casimir / (9 * mu_R_self**2))

print(f"    μ_R = 3√(2λ)/L_X = {mu_R_self:.1f} GeV")
print(f"    L_*(self-consistent) = {L_star_self:.4f} GeV⁻¹")
print(f"    Target L_X = {L_X:.4f} GeV⁻¹")
print(f"    Ratio: {L_star_self/L_X:.3f}")
print()

# What λ_R gives L_* = L_X exactly?
# L_* = sqrt(2A/(9μ_R²)) and μ_R = 3√(2λ)/L_*
# L_*² = 2A/(9 × 18λ/L_*²) = 2A×L_*²/(162λ)
# 1 = 2A/(162λ) → λ = 2A/162 = A/81
lambda_exact = A_casimir / 81
mu_R_exact = 3 * np.sqrt(2 * lambda_exact) / L_X
print(f"  SELF-CONSISTENT SOLUTION:")
print(f"    λ_R = A/81 = {lambda_exact:.4f}")
print(f"    μ_R = {mu_R_exact:.1f} GeV")
print(f"    This gives L_* = L_X exactly.")
print(f"    Compare: λ_SM = {lambda_SM:.4f}")
print(f"    Ratio λ_R/λ_SM = {lambda_exact/lambda_SM:.2f}")

# =====================================================================
header("SECTION 4: Approach D — μ_R from Electroweak Symmetry Breaking")

print("  If the R-field IS the Higgs field (gauge-Higgs unification),")
print("  then μ_R = μ_Higgs = m_H/√2 = {:.1f} GeV".format(m_H/np.sqrt(2)))
print()

mu_R_Higgs = m_H / np.sqrt(2)
L_star_Higgs = np.sqrt(2 * A_casimir / (9 * mu_R_Higgs**2))

print(f"  μ_R(Higgs) = m_H/√2 = {mu_R_Higgs:.1f} GeV")
print(f"  L_*(Higgs) = {L_star_Higgs:.4f} GeV⁻¹")
print(f"  Target L_X = {L_X:.4f} GeV⁻¹")
print(f"  Ratio: {L_star_Higgs/L_X:.2f}")
print(f"  M_KK(Higgs) = {2*np.pi/L_star_Higgs:.0f} GeV")

# =====================================================================
header("SECTION 5: Summary")

print(f"  ╔═══════════════════════════════════════════════════════════╗")
print(f"  ║  L_X STABILIZATION: μ_R DETERMINATION                  ║")
print(f"  ╠═══════════════════════════════════════════════════════════╣")
print(f"  ║                                                         ║")
print(f"  ║  Approach       μ_R (GeV)  L_*/L_X  Comment            ║")
print(f"  ║  ─────────────  ─────────  ───────  ────────────────── ║")
print(f"  ║  A. CW (SM)       {mu_R_CW:6.1f}    {L_star_CW/L_X:5.2f}   SM loops          ║")
print(f"  ║  B. Dim. trans.   varies    varies   g-dependent        ║")
print(f"  ║  C. Self-cons.    {mu_R_exact:6.1f}    {1.0:5.2f}   λ_R = {lambda_exact:.3f}       ║")
print(f"  ║  D. Higgs=R       {mu_R_Higgs:6.1f}    {L_star_Higgs/L_X:5.2f}   gauge-Higgs unif. ║")
print(f"  ║                                                         ║")
print(f"  ║  BEST: Approach D (gauge-Higgs unification)             ║")
print(f"  ║    μ_R = m_H/√2 gives L_*/L_X = {L_star_Higgs/L_X:.2f}               ║")
print(f"  ║    Within O(1) of target — natural EW-scale minimum     ║")
print(f"  ║                                                         ║")
print(f"  ║  STATUS: PARTIAL → CLOSE                                ║")
print(f"  ║  If R-field IS the Higgs (A₅ mode in gauge-Higgs       ║")
print(f"  ║  unification), then μ_R = m_H/√2 is fixed and L_X     ║")
print(f"  ║  stabilization follows from EWSB.                       ║")
print(f"  ╚═══════════════════════════════════════════════════════════╝")
